### ISSUE TITLE
请问代码是没有贴全吗

### ISSUE THREAD

**Issue by poemcoding** [sinx-wang/dealCourtDocs#1]
在get_data.py中得到搜索结果后好像就没有进一步的下载操作了，还有请问下deal.py这个文件是完成什么功能的？谢谢

**Comment by sinx-wang** [comment]
是的……最近工作太忙（因为公务员工作和代码本来就没啥关系，这两天又在办公场所搬迁手忙脚乱）没填坑，过几天放假一定不鸽（捂脸



发自我的小米手机
在 poemcoding ***@***.***>，2021年4月26日 20:18写道：

在get_data.py中得到搜索结果后好像就没有进一步的下载操作了，还有请问下deal.py这个文件是完成什么功能的？谢谢

**Comment by poemcoding** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        哈哈好的
        
    在2021年4月26日 ***@***.***> 写道： 




是的……最近工作太忙（因为公务员工作和代码本来就没啥关系，这两天又在办公场所搬迁手忙脚乱）没填坑，过几天放假一定不鸽（捂脸















发自我的小米手机



在 poemcoding ***@***.***>，2021年4月26日 20:18写道：







在get_data.py中得到搜索结果后好像就没有进一步的下载操作了，还有请问下deal.py这个文件是完成什么功能的？谢谢

**Comment by sinx-wang** [comment]
新写了一部分，功能大体差不多啦
